// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hawtfcebtysrafdingsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhd3RmY2VidHlzcmFmZGluZ3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjI5NzUsImV4cCI6MjA3NDQ5ODk3NX0.1ItU3M9GzbRiv3Ef2SoAGlEVsBAT2e6K2FUYUyAYgkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});